server {
    listen 3000 ssl;
    server_name localhost;
    ssl_certificate /etc/nginx/ssl/localhost.crt;
    ssl_certificate_key /etc/nginx/ssl/localhost.key;
    root /usr/share/nginx/html;
    index taskpane.html;
    location / {
        try_files $uri $uri/ /taskpane.html;
    }
    location ~* \.(js|css|png|ico|xml|html)$ {
        add_header Cache-Control "no-cache";
    }
}
